#!/bin/dash

# When adding files to the index, we have to consider the following

# (1) Empty input?
# (2) Does the .girt directory exist?
# (3) Does the file even exist?
# (4) The filename should begin with an alphanumeric character
# (5) The file we are adding should exist in the working directory

if test ! -d ".girt"
then
    echo "girt-add: error: girt repository directory .girt not found"
    exit 1
fi

if [ $# -eq 0 ]
then
    echo "usage: girt-add <filenames>"
    exit 1
fi

for FILE in "$@"
do
    # Note, only ordinary files in the current directory can be added
    validname=$(echo "$FILE" | grep -E '^[a-zA-Z0-9]' | wc -l)
    if test ! -d ".girt"
    then
        echo "girt-add: error: girt repository directory .girt not found"
        exit 1
    
    elif [ $validname -eq 0 ]
    then
        echo "girt-add: error: invalid filename '$FILE'"
        exit 1
    
    elif test -d "$FILE"
    then
        echo "girt-add: error: '$FILE' is not a regular file"
        exit 1
    
    elif test ! -f "$FILE" && test ! -f ".girt/index/$FILE"
    then
        echo "girt-add: error: can not open '$FILE'"
        exit 1
    fi
done

for FILE in "$@"
do
    # Now to be more specific, girt-add should add 'changes' to the index
    if test ! -f "$FILE" && test -f ".girt/index/$FILE"
    then
        rm ".girt/index/$FILE"
    else
        cp "$FILE" ".girt/index"
    fi
done
exit 0
